services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - geoip-network-go

  app:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - geoip-network-go
    environment:
      - REDIS_ADDRESS=redis:6379

  test:
    build: .
    depends_on:
      - redis
    networks:
      - geoip-network-go
    environment:
      - REDIS_ADDRESS=redis:6379
    volumes:
      - ./:/app
    working_dir: /app
    command: go test -v ./...

networks:
  geoip-network-go:
    driver: bridge
